#!/usr/bin/env python3
"""wiki-graph (ADDON) — render the knowledge wiki as an interactive graph.

OPTIONAL visualization addon, NOT wiki content. Reads pages + their [[wikilinks]] and
emits ONE self-contained HTML file with a dependency-free canvas force-graph: nodes =
pages (size = #links), edges = links, hover focuses a node + its neighbours, click
shows the page's Summary. No external/CDN/library loads — works as a plain file://.
Output is git-ignored and regenerated by the post-commit hook. Look inspired by Quartz.

Layout: d3-force-style simulation (link strength 1/min(degree) so hubs don't crush
their neighbours, degree-scaled repulsion, collision, weak centering), seeded by a
BFS phyllotaxis so neighbours start near each other; pre-relaxed before first paint
and auto-fitted to the viewport.

Usage:  python wiki-graph.py [WIKI_ROOT] [OUT_HTML]
"""
import os, re, sys, glob, json, html

ROOT = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.getcwd()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "wiki-graph.html")
WIKI = os.path.join(ROOT, "Wiki")

mds = glob.glob(os.path.join(WIKI, "**", "*.md"), recursive=True)
def slug(f): return os.path.splitext(os.path.basename(f))[0]
def cat(f):
    p = os.path.relpath(f, WIKI).replace("\\", "/")
    return p.split("/")[0] if "/" in p else "root"
def summary(txt):
    m = re.search(r'^\*\*Summary\*\*:\s*(.+)$', txt, re.M)
    if m: return m.group(1).strip()
    for ln in txt.splitlines():
        ln = ln.strip()
        if ln and ln[0] not in "#*-": return ln
    return ""

# dedupe slugs (e.g. several index.md): keep the shallowest path — wikilinks resolve there
best = {}
for f in mds:
    s = slug(f); d = len(os.path.relpath(f, WIKI).split(os.sep))
    if s not in best or d < len(os.path.relpath(best[s], WIKI).split(os.sep)):
        best[s] = f
dropped = len(mds) - len(best)
mds = sorted(best.values())

pages = {slug(f) for f in mds}
nodes, edges, seen = [], [], set()
link_re = re.compile(r'\[\[([^\]|#]+)')
for f in mds:
    s = slug(f); txt = open(f, encoding="utf-8", errors="replace").read()
    nodes.append({"id": s, "label": s, "group": cat(f), "summary": summary(txt)[:400]})
    for m in link_re.finditer(txt):
        t = m.group(1).strip().split("/")[-1]
        if t in pages and t != s and (s, t) not in seen and (t, s) not in seen:
            seen.add((s, t)); edges.append([s, t])

deg = {}
for a, b in edges:
    deg[a] = deg.get(a, 0) + 1; deg[b] = deg.get(b, 0) + 1
for n in nodes:
    n["deg"] = deg.get(n["id"], 0)

DOC = r"""<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Knowledge Wiki Graph</title>
<style>
 :root{--bg:#faf8f8;--panel:#fff;--text:#33373d;--muted:#6b7280;--accent:#3b6e8f;--border:#e6e3e0;--edge:rgba(120,130,145,0.28)}
 @media(prefers-color-scheme:dark){:root{--bg:#15161a;--panel:#1c1e24;--text:#d7dbe0;--muted:#8a909b;--accent:#7fa6c4;--border:#2a2d35;--edge:rgba(150,160,175,0.22)}}
 *{box-sizing:border-box}html,body{margin:0;height:100%}
 body{font:14px Inter,system-ui,sans-serif;display:flex;height:100vh;background:var(--bg);color:var(--text)}
 #c{flex:1;display:block;cursor:grab}#c:active{cursor:grabbing}
 #side{width:340px;flex:none;padding:20px;overflow:auto;background:var(--panel);border-left:1px solid var(--border)}
 #side .cat{font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:var(--accent)}
 #side h2{font-size:16px;font-weight:500;margin:6px 0 12px;word-break:break-word}
 #side .body{color:var(--muted);line-height:1.65}
 #cap{position:absolute;top:12px;left:16px;font-size:12px;color:var(--muted)}
 #legend{position:absolute;top:12px;right:360px;font-size:11px;color:var(--muted);text-align:right}
 #legend span{margin-left:10px}#legend i{display:inline-block;width:8px;height:8px;border-radius:50%;vertical-align:1px;margin-right:3px}
</style></head><body>
<canvas id="c"></canvas>
<div id="cap">__N__ Seiten · __E__ Links · ziehen/scrollen · hover = fokus+info · halten = Nachbarn auffächern · doppelklick = einpassen</div>
<div id="legend">
 <span><i style="background:#8b7fe8"></i>roster</span><span><i style="background:#4fbf95"></i>experience</span><span><i style="background:#5b9bd5"></i>knowledge</span><span><i style="background:#dd8b5e"></i>projects</span><span><i style="background:#d3aa4e"></i>guardrails</span>
</div>
<div id="side"><p style="color:var(--muted)">Klicke einen Knoten für die Zusammenfassung.</p></div>
<script>
var ND=__NODES__, ED=__EDGES__;
var COL={roster:'#8b7fe8',experience:'#4fbf95',knowledge:'#5b9bd5',projects:'#dd8b5e',guardrails:'#d3aa4e',adr:'#b78bd0',journal:'#9aa0ad',root:'#9aa0ad'};
var cv=document.getElementById('c'),ctx=cv.getContext('2d'),side=document.getElementById('side');
var css=getComputedStyle(document.body);
var TXT=css.getPropertyValue('--text').trim(),EDGE=css.getPropertyValue('--edge').trim(),ACC=css.getPropertyValue('--accent').trim();
var idx={};ND.forEach(function(n,i){idx[n.id]=i;});
var E=ED.map(function(e){return [idx[e[0]],idx[e[1]]];}).filter(function(p){return p[0]!=null&&p[1]!=null;});
var adj=ND.map(function(){return [];});
E.forEach(function(p){adj[p[0]].push(p[1]);adj[p[1]].push(p[0]);});
ND.forEach(function(n){n.r=6+Math.sqrt(n.deg||0)*2.4;n.K=56+22*Math.sqrt(n.deg||0);n.vx=0;n.vy=0;
 n.ox=0;n.oy=0;n.tx=0;n.ty=0;n.fa=1;n._sa=0;n._sr=0;}); // Anzeige-Offset (Spread beim Halten) + weicher Fokus-Faktor

/* Startlayout: BFS vom groessten Hub jeder Komponente, auf einer Phyllotaxis-Spirale
   abgelegt — Graph-Nachbarn starten dadurch raeumlich nahe beieinander. */
var order=[],vis=ND.map(function(){return false;});
ND.map(function(n,i){return i;}).sort(function(a,b){return ND[b].deg-ND[a].deg;}).forEach(function(s){
 if(vis[s])return;vis[s]=true;var q=[s];
 while(q.length){var v=q.shift();order.push(v);adj[v].forEach(function(w){if(!vis[w]){vis[w]=true;q.push(w);}});}
});
order.forEach(function(ni,k){var n=ND[ni],R=16*Math.sqrt(k+0.5),A=k*2.39996323;
 n.x=R*Math.cos(A);n.y=R*Math.sin(A);});

/* Kraefte im d3-force-Stil. Entscheidend: Federstaerke = 1/min(grad), sonst zieht
   ein Hub mit 40 Links seine Nachbarn mit 40-facher Kraft durch sich hindurch. */
var EP=E.map(function(p){var a=ND[p[0]],b=ND[p[1]],da=Math.max(1,a.deg),db=Math.max(1,b.deg);
 return {a:a,b:b,dist:60+a.r+b.r+6*Math.min(5,Math.min(da,db)),str:1/Math.min(da,db),bias:da/(da+db)};});
var alpha=1,alphaTarget=0,ALPHA_MIN=0.001,ALPHA_DECAY=0.025,VEL_DECAY=0.35;
var cam={x:0,y:0,z:1},drag=null,dragI=-1,focusK=0,dragging=false,moved=false,panning=false,last={x:0,y:0},down=null,hov=-1;
function tick(){
 alpha+=(alphaTarget-alpha)*ALPHA_DECAY;
 var i,j,a,b,dx,dy,d2,d,f,e,n=ND.length;
 for(i=0;i<EP.length;i++){e=EP[i];a=e.a;b=e.b;
  dx=(b.x+b.vx)-(a.x+a.vx);dy=(b.y+b.vy)-(a.y+a.vy);d=Math.sqrt(dx*dx+dy*dy)||1e-6;
  f=(d-e.dist)/d*alpha*e.str;
  b.vx-=dx*f*e.bias;b.vy-=dy*f*e.bias;a.vx+=dx*f*(1-e.bias);a.vy+=dy*f*(1-e.bias);}
 for(i=0;i<n;i++){a=ND[i];
  for(j=i+1;j<n;j++){b=ND[j];
   dx=b.x-a.x;dy=b.y-a.y;d2=dx*dx+dy*dy;
   if(d2<1){dx=((i*7+j)%13-6)*0.2+0.1;dy=((i*11+j)%13-6)*0.2-0.1;d2=dx*dx+dy*dy;}
   d=Math.sqrt(d2);
   var rr=a.r+b.r+5;
   if(d2<250000){f=alpha*a.K*b.K/Math.max(d2,rr*rr); // Abstossung innerhalb rr kappen, sonst explodiert der Graph beim Drag
    var ux=dx/d,uy=dy/d;
    a.vx-=ux*f;a.vy-=uy*f;b.vx+=ux*f;b.vy+=uy*f;}
   if(d<rr){var ov=(rr-d)/d,ka=a===drag?0:(b===drag?1:0.5),kb=1-ka; // Drag-Knoten ist unverrueckbar
    a.x-=dx*ov*ka;a.y-=dy*ov*ka;b.x+=dx*ov*kb;b.y+=dy*ov*kb;}}
  a.vx+=-a.x*0.02*alpha;a.vy+=-a.y*0.02*alpha;}
 for(i=0;i<n;i++){a=ND[i];if(a===drag){a.vx=0;a.vy=0;continue;} // Drag-Knoten darf keine Kraft "aufladen"
  a.vx*=(1-VEL_DECAY);a.vy*=(1-VEL_DECAY);
  var sp=Math.sqrt(a.vx*a.vx+a.vy*a.vy);if(sp>30){a.vx*=30/sp;a.vy*=30/sp;} // Sicherheitsnetz: max Schrittweite
  a.x+=a.vx;a.y+=a.vy;}
}
for(var pre=0;pre<250;pre++)tick(); // vorentspannen: Nutzer sieht nie den unsortierten Zustand
function autofit(){var W=cv.clientWidth,H=cv.clientHeight;if(!ND.length||!W||!H)return;
 var x0=1e9,x1=-1e9,y0=1e9,y1=-1e9;
 ND.forEach(function(n){x0=Math.min(x0,n.x-n.r);x1=Math.max(x1,n.x+n.r);y0=Math.min(y0,n.y-n.r);y1=Math.max(y1,n.y+n.r);});
 var z=Math.min(1.6,0.9*Math.min(W/(x1-x0+120),H/(y1-y0+120)));
 cam.z=z;cam.x=-(x0+x1)/2*z;cam.y=-(y0+y1)/2*z;}
var fitted=false;
autofit();if(cv.clientWidth&&cv.clientHeight)fitted=true;
function focusSet(){if(hov<0)return null;var s={};s[hov]=1;adj[hov].forEach(function(k){s[k]=1;});return s;}
/* Beim Greifen eines Knotens: die "kleineren" Nachbarn auf Ringe verteilen (nach
   aktuellem Winkel sortiert, damit sich moeglichst keine Kanten kreuzen).
   Nachbarn mit gleichem/hoeherem Grad — allen voran der Top-Hub — sind selbst
   Fixsterne und werden NICHT mit herausgezogen.
   Normale Knoten: kompakte konzentrische Ringe. Der Top-Hub (index) selbst:
   EIN grosser Ring um ihn — der Sternen-Effekt. */
var spreadList=[],HUB=0;ND.forEach(function(n,i){if(n.deg>ND[HUB].deg)HUB=i;});
function computeSpread(hi){var h=ND[hi];
 spreadList=adj[hi].filter(function(k){return ND[k].deg<h.deg;});
 if(!spreadList.length)return;
 var arr=spreadList.slice().sort(function(p,q){var A=ND[p],B=ND[q];
  return Math.atan2(A.y-h.y,A.x-h.x)-Math.atan2(B.y-h.y,B.x-h.x);});
 if(hi===HUB){
  var R=Math.max(70+h.r+24,arr.length*40/6.2832);
  var a0=Math.atan2(ND[arr[0]].y-h.y,ND[arr[0]].x-h.x);
  arr.forEach(function(k,ii){var n=ND[k];n._sa=a0+ii*6.2832/arr.length;n._sr=R;});
 }else{
  var i=0,R2=70+h.r+24;
  while(i<arr.length){
   var cap=Math.max(6,Math.floor(6.2832*R2/44)),take=Math.min(cap,arr.length-i);
   var b0=Math.atan2(ND[arr[i]].y-h.y,ND[arr[i]].x-h.x);
   for(var k=0;k<take;k++){var n=ND[arr[i+k]];n._sa=b0+k*6.2832/take;n._sr=R2;}
   i+=take;R2+=64;
  }
 }
}
/* Weiche Uebergaenge: Fokus-Abdunkeln und Spread-Offsets werden pro Frame gelerpt,
   nichts springt. Rein kosmetisch — die Physik laeuft auf den Basispositionen weiter. */
function anim(){
 var fs=focusSet(),i,n;
 focusK+=((hov>=0?1:0)-focusK)*0.15;
 for(i=0;i<ND.length;i++){n=ND[i];n.tx=0;n.ty=0;
  var tf=!fs?1:(fs[i]?1:0.12);n.fa+=(tf-n.fa)*0.18;}
 if(dragging&&drag&&dragI>=0){var h=drag;
  spreadList.forEach(function(k){n=ND[k];
   n.tx=h.x+n._sr*Math.cos(n._sa)-n.x;n.ty=h.y+n._sr*Math.sin(n._sa)-n.y;});}
 for(i=0;i<ND.length;i++){n=ND[i];n.ox+=(n.tx-n.ox)*0.15;n.oy+=(n.ty-n.oy)*0.15;}
}
function draw(){
 var W=cv.width=cv.clientWidth,H=cv.height=cv.clientHeight,i,a,b;
 if(!fitted&&W&&H){fitted=true;autofit();} // Erst-Fit nachholen, falls Canvas beim Laden noch 0x0 war
 ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(W/2+cam.x,H/2+cam.y);ctx.scale(cam.z,cam.z);
 var fs=focusSet();
 for(i=0;i<E.length;i++){a=ND[E[i][0]];b=ND[E[i][1]];
  var ax=a.x+a.ox,ay=a.y+a.oy,bx=b.x+b.ox,by=b.y+b.oy;
  ctx.globalAlpha=Math.min(a.fa,b.fa); // Kanten dunkeln weich mit ihren Endpunkten ab
  ctx.strokeStyle=EDGE;ctx.lineWidth=1/cam.z;
  ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke();
  if(fs&&(E[i][0]===hov||E[i][1]===hov)&&focusK>0.02){ // Akzent blendet mit focusK ein
   ctx.globalAlpha=focusK;ctx.strokeStyle=ACC;ctx.lineWidth=1.8/cam.z;
   ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke();}}
 for(i=0;i<ND.length;i++){a=ND[i];var px=a.x+a.ox,py=a.y+a.oy;
  ctx.globalAlpha=a.fa;
  ctx.fillStyle=COL[a.group]||'#9aa0ad';ctx.beginPath();ctx.arc(px,py,a.r,0,6.2832);ctx.fill();
  if(i===hov){ctx.strokeStyle=ACC;ctx.lineWidth=2/cam.z;ctx.stroke();}
  var la=(fs&&fs[i])||cam.z>=1.2?1:Math.max(0,Math.min(1,(a.r*cam.z-10)/5)); // Labels blenden mit Groesse*Zoom ein
  la*=a.fa;
  if(la>0.02){ctx.globalAlpha=la;ctx.fillStyle=TXT;ctx.font=(12/cam.z)+'px Inter,system-ui';ctx.textAlign='center';ctx.fillText(a.label,px,py+a.r+11/cam.z);}}
 ctx.restore();ctx.globalAlpha=1;
}
function loop(){if(alpha>ALPHA_MIN||alphaTarget>0)tick();anim();draw();requestAnimationFrame(loop);}
function world(ev){var rc=cv.getBoundingClientRect();return {x:(ev.clientX-rc.left-cv.clientWidth/2-cam.x)/cam.z,y:(ev.clientY-rc.top-cv.clientHeight/2-cam.y)/cam.z};}
function hit(w){for(var i=ND.length-1;i>=0;i--){var n=ND[i],dx=n.x+n.ox-w.x,dy=n.y+n.oy-w.y;if(dx*dx+dy*dy<=(n.r+3)*(n.r+3))return i;}return -1;}
var lastInfo=-1;
function showInfo(i){if(i===lastInfo)return;lastInfo=i;
 if(i<0){side.innerHTML='<p style="color:var(--muted)">Klicke einen Knoten für die Zusammenfassung.</p>';return;}
 var n=ND[i];side.innerHTML='<div class="cat">'+esc(n.group)+'</div><h2>'+esc(n.label)+'</h2><div class="body">'+esc(n.summary||'(keine Summary)')+'</div>';}
cv.addEventListener('mousemove',function(ev){var w=world(ev);
 if(dragging&&drag){
  /* Fixstern: der gehaltene Knoten bleibt stehen. Erst ab ~6px Mausweg wird es
     ein echter Drag — dann folgt er dem Cursor und die Physik heizt auf. */
  if(!moved&&down&&(Math.abs(ev.clientX-down.x)>6||Math.abs(ev.clientY-down.y)>6)){
   moved=true;alphaTarget=0.3;if(alpha<0.3)alpha=0.3;}
  if(moved){drag.x=w.x;drag.y=w.y;drag.vx=0;drag.vy=0;}
  return;}
 if(panning){cam.x+=ev.clientX-last.x;cam.y+=ev.clientY-last.y;last={x:ev.clientX,y:ev.clientY};return;}
 hov=hit(w);if(hov>=0)showInfo(hov);}); // Hover zeigt die Info rechts sofort; beim Verlassen bleibt sie stehen
cv.addEventListener('mousedown',function(ev){last={x:ev.clientX,y:ev.clientY};down={x:ev.clientX,y:ev.clientY};var h=hit(world(ev));
 if(h>=0){drag=ND[h];dragI=h;hov=h;dragging=true;moved=false;computeSpread(h);}else{panning=true;}});
window.addEventListener('mouseup',function(ev){
 if(down&&Math.abs(ev.clientX-down.x)<4&&Math.abs(ev.clientY-down.y)<4){var h=hit(world(ev));
  hov=h;showInfo(h);}
 drag=null;dragI=-1;dragging=false;moved=false;panning=false;down=null;alphaTarget=0;});
cv.addEventListener('dblclick',function(){autofit();});
cv.addEventListener('wheel',function(ev){ev.preventDefault();var f=ev.deltaY<0?1.1:0.9;cam.z=Math.max(0.15,Math.min(4,cam.z*f));},{passive:false});
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
loop();
</script></body></html>"""
out = (DOC.replace("__NODES__", json.dumps(nodes, ensure_ascii=False))
          .replace("__EDGES__", json.dumps(edges, ensure_ascii=False))
          .replace("__N__", str(len(nodes))).replace("__E__", str(len(edges))))
open(OUT, "w", encoding="utf-8").write(out)
print(f"wiki-graph: {len(nodes)} nodes, {len(edges)} edges"
      + (f" ({dropped} duplicate slugs dropped)" if dropped else "") + f" -> {OUT}")
