#!/usr/bin/env python3
"""gen-adapters — generate the thin Claude subagent adapters FROM the role briefs.

The role brief (Wiki/roster/role-X.md) is the single source of truth. The adapter
(~/.claude/agents/X.md) is a DERIVED artifact that just points at the brief — so it
can't drift. Re-run after editing any role brief (idempotent).

Usage:  python gen-adapters.py [WIKI_ROOT] [AGENTS_OUT]
  WIKI_ROOT  default: current dir
  AGENTS_OUT default: ~/.claude/agents
Only pool roles (Wiki/roster/role-*.md) are generated; project-local domain agents
live in their repo's .claude/agents and are untouched.
"""
import os, re, sys, glob

ROOT = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.getcwd()
OUT  = os.path.abspath(sys.argv[2]) if len(sys.argv) > 2 else os.path.expanduser("~/.claude/agents")
os.makedirs(OUT, exist_ok=True)

def field(txt, name):
    m = re.search(r'^\*\*' + re.escape(name) + r'\*\*:\s*(.+)$', txt, re.M)
    return m.group(1).strip() if m else None

written = []
for f in sorted(glob.glob(os.path.join(ROOT, "Wiki", "roster", "role-*.md"))):
    slug = os.path.basename(f)[len("role-"):-3]
    txt = open(f, encoding="utf-8").read()
    tm = re.search(r'^#\s*Role:\s*(.+)$', txt, re.M)
    title = tm.group(1).strip() if tm else slug
    summary = (field(txt, "Summary") or f"the {slug} role").rstrip('.')
    name = field(txt, "Name")
    tools_raw = field(txt, "Tools (Claude)") or ""
    tools = tools_raw.split("—")[0].split(" - ")[0]
    tools = re.sub(r'\([^)]*\)', '', tools)                       # list before any note; drop parentheticals
    tools = " ".join(tools.split()).strip().rstrip('.').strip()   # normalize whitespace
    nm = f" ({name.rstrip('.')})" if name else ""
    disp = ROOT.replace("\\", "/")
    adapter = f"""---
name: {slug}
description: >-
  {summary}.
tools: {tools}
---

You are the **{title}**{nm}. Your canonical, tool-neutral role brief is:

`{disp}/Wiki/roster/role-{slug}.md`

Read it first and operate **exactly** by it — its procedure, output contract, hand-offs,
and tool/boundary limits. Do not deviate.

Fallback (brief unavailable): act per the summary above; ask the user if anything is unclear.

<!-- GENERATED by scripts/gen-adapters.py from role-{slug}.md — do not hand-edit; change the brief. -->
"""
    open(os.path.join(OUT, slug + ".md"), "w", encoding="utf-8").write(adapter)
    written.append(slug)

print(f"gen-adapters: wrote {len(written)} adapters -> {OUT}")
print("  " + ", ".join(written))
